//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrifAustria
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrifAustriaEFContainer : DbContext
    {
        public CrifAustriaEFContainer()
            : base("name=CrifAustriaEFContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProductRequest> ProductRequests { get; set; }
        public virtual DbSet<SuccessStoryRequest> SuccessStoryRequests { get; set; }
        public virtual DbSet<contactUs> contactUs { get; set; }
        public virtual DbSet<newsletterSubscription> newsletterSubscriptions { get; set; }
        public virtual DbSet<sheduleConsultation> sheduleConsultations { get; set; }
    }
}
