//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrifAustria
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsletterSubscription
    {
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string industry { get; set; }
        public string jobTitle { get; set; }
        public string company { get; set; }
        public string agreement { get; set; }
        public string newsletter { get; set; }
        public string culture { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    }
}
