//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrifAustria
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuccessStoryRequest
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Industry { get; set; }
        public string JobTitle { get; set; }
        public string Company { get; set; }
        public string Agreement { get; set; }
        public string Newsletter { get; set; }
        public string Culture { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ProductName { get; set; }
    }
}
